import { MasteryDimension, QuestionType, TrainingLesson, TrainingQuestion } from './training.models';

type RawOption = readonly [id: string, label: string, detail: string];
const q = (id: string, type: QuestionType, dimension: MasteryDimension, prompt: string, correctOptionId: string,
  explanation: string, options: readonly RawOption[], code?: string, hint = 'Relis le code et identifie le rôle de chaque élément.'): TrainingQuestion => ({
  id, type, dimension, prompt, correctOptionId, explanation, code, hint,
  misconception: `La réponse choisie ne correspond pas au modèle Angular décrit ici : ${explanation}`,
  remediation: ['Revoir le modèle mental dans le Lab', 'Reproduire l’exemple dans un composant minimal', 'Expliquer à voix haute pourquoi la bonne réponse fonctionne'],
  options: options.map(([optionId, label, detail]) => ({ id: optionId, label, detail })),
});
const o = (id: string, label: string, detail: string): RawOption => [id, label, detail];

export const FUNDAMENTALS_LESSONS: readonly TrainingLesson[] = [
  { id: 'standalone-bootstrap', title: 'Standalone et bootstrap', category: 'Fondamentaux', icon: 'pi pi-power-off', description: 'Comprendre le démarrage moderne d’Angular et les dépendances explicites.', definition: 'Un composant standalone déclare directement les composants, directives et pipes nécessaires à son template. Le bootstrap est l’étape distincte qui crée l’application, son injecteur racine et son premier composant.', mentalModel: 'imports répond à « que peut utiliser ce template ? » ; providers à « que peut injecter cette portée ? » ; bootstrapApplication à « par quel composant l’application commence-t-elle ? ».', rule: 'Garde les dépendances de template locales au composant et réserve la configuration globale aux providers du bootstrap.', labRoute: '/lab/fondamentaux/standalone-bootstrap', questions: [
    q('sb1','quiz','Compréhension','Que signifie standalone: true ?', 'b','Le composant peut être importé directement sans déclaration dans un NgModule.',[o('a','Il fonctionne sans Angular','Il reste géré par Angular.'),o('b','Il est importable directement','Aucun NgModule de déclaration requis.'),o('c','Il ne peut rien importer','Il possède justement un tableau imports.')]),
    q('sb2','code-completion','Mise en pratique','Quel appel démarre cette application ?', 'a','bootstrapApplication crée l’application à partir du composant racine et des providers globaux.',[o('a','bootstrapApplication','Démarrage standalone.'),o('b','createComponent','Création manuelle isolée.'),o('c','bootstrapModule','Démarrage fondé sur un NgModule.')],`bootstrapApplication(AppComponent, {\n  providers: [provideRouter(routes)]\n});`),
    q('sb3','code-diagnostic','Lecture de code','Pourquoi <router-outlet> est-il inconnu ?', 'c','RouterOutlet doit être ajouté aux imports du composant qui l’utilise.',[o('a','La route racine manque','Cela ne bloque pas la compilation du template.'),o('b','standalone doit être retiré','Ce n’est pas nécessaire.'),o('c','RouterOutlet manque dans imports','La directive est invisible dans ce template.')],`@Component({ standalone: true,\n  template: '<router-outlet />', imports: [] })`),
    q('sb4','architecture','Décision','Où déclarer un intercepteur utilisé dans toute l’application ?', 'a','Une configuration globale appartient aux providers de bootstrapApplication ou à ApplicationConfig.',[o('a','Dans ApplicationConfig','Portée globale centralisée.'),o('b','Dans chaque composant','Duplication et portées locales.'),o('c','Dans le HTML','Le template ne configure pas l’injection.')]),
    q('sb5','quiz','Compréhension','À quoi sert imports dans un composant standalone ?', 'b','Il rend disponibles les composants, directives et pipes utilisés par son template.',[o('a','À enregistrer tous les services','Les services utilisent les providers.'),o('b','À exposer les dépendances du template','Composants, directives et pipes.'),o('c','À charger le CSS global','Les styles ont leur propre configuration.')]),
  ]},
  { id: 'composants-templates', title: 'Composants et templates', category: 'Fondamentaux', icon: 'pi pi-box', description: 'Relier une classe, ses métadonnées et sa portion d’interface.', definition: 'Un composant Angular est une classe associée à des métadonnées et à un template. Angular crée une instance de cette classe lorsqu’une vue doit être rendue et utilise ses propriétés pour alimenter le template.', mentalModel: 'Le composant pilote une portion cohérente d’interface ; le template décrit cette interface ; les services portent les accès aux données et les traitements partagés.', rule: 'Découpe selon les responsabilités et non selon un nombre arbitraire de lignes.', labRoute: '/lab/fondamentaux/composants-templates', questions: [
    q('ct1','quiz','Compréhension','Quel est le rôle principal d’un composant ?', 'b','Il porte l’état et le comportement nécessaires à une portion d’interface rendue par son template.',[o('a','Remplacer la base de données','Ce n’est pas une responsabilité UI.'),o('b','Piloter une portion d’interface','Classe et template coopèrent.'),o('c','Configurer le serveur','Cela appartient au backend.')]),
    q('ct2','code-diagnostic','Lecture de code','Pourquoi <user-card> ne crée-t-il pas ce composant ?', 'a','La balise doit correspondre exactement au selector app-user-card.',[o('a','La balise attendue est <app-user-card>','Elle correspond au selector.'),o('b','Il manque un service','Sans rapport.'),o('c','La classe doit se nommer user-card','Le nom TypeScript ne définit pas la balise.')],`@Component({ selector: 'app-user-card' })`),
    q('ct3','code-completion','Mise en pratique','Quelle syntaxe affiche la propriété name ?', 'c','L’interpolation {{ name }} évalue la propriété et produit du texte.',[o('a','[name]','Binding de propriété incomplet.'),o('b','(name)','Syntaxe d’événement.'),o('c','{{ name }}','Interpolation de texte.')],`<h2>___</h2>`),
    q('ct4','architecture','Décision','Une carte de 500 lignes gère UI, API et règles métier. Que faire ?', 'b','Il faut séparer l’accès aux données et découper les responsabilités UI cohérentes.',[o('a','Tout conserver','La complexité reste concentrée.'),o('b','Séparer selon les responsabilités','UI, données et métier évoluent séparément.'),o('c','Tout déplacer dans le HTML','Le template deviendrait illisible.')]),
    q('ct5','quiz','Compréhension','Quand Angular crée-t-il une instance de composant ?', 'a','Lorsqu’il doit entrer dans l’arbre rendu via un template, une route ou une création dynamique.',[o('a','Quand il entre dans l’arbre rendu','Une vue a besoin de son instance.'),o('b','Dès son import TypeScript','Un import ne crée aucun objet.'),o('c','Au build uniquement','Les instances existent au runtime.')]),
  ]},
  { id: 'data-binding', title: 'Data binding', category: 'Fondamentaux', icon: 'pi pi-link', description: 'Faire circuler les données entre classe, DOM et composants.', definition: 'Le data binding relie l’état TypeScript au template. L’interpolation affiche du texte, les crochets transmettent une valeur vers une propriété et les parenthèses font remonter un événement.', mentalModel: 'Données vers la vue : [] ; action de la vue vers la classe : () ; les deux sens combinés : [()].', rule: 'Choisis la syntaxe qui rend le sens du flux visible et évite les manipulations manuelles du DOM.', labRoute: '/lab/fondamentaux/data-binding', questions: [
    q('db1','quiz','Compréhension','Quelle syntaxe transmet un booléen à la propriété DOM disabled ?', 'a','[disabled]="isSaving" est un property binding typé de la classe vers la vue.',[o('a','[disabled]="isSaving"','Property binding.'),o('b','(disabled)="isSaving"','Écoute d’événement.'),o('c','#disabled','Référence de template.')]),
    q('db2','code-diagnostic','Lecture de code','Que se passe-t-il au clic ?', 'b','Le gestionnaire incrémente count puis Angular actualise l’interpolation.',[o('a','Rien','Angular évalue les bindings.'),o('b','Le nombre augmente','Événement, état, puis vue.'),o('c','La page recharge','Aucun submit ici.')],`<button (click)="count = count + 1">{{ count }}</button>`),
    q('db3','code-completion','Mise en pratique','Comment recevoir chaque saisie sans ngModel ?', 'c','(input) écoute l’événement émis par le champ.',[o('a','[input]','Liaison de propriété.'),o('b','{{ input }}','Interpolation.'),o('c','(input)','Liaison d’événement.')],`<input ___="onNameChange($event)" />`),
    q('db4','architecture','Décision','Quelle approche choisir pour un formulaire métier complexe ?', 'b','Les formulaires réactifs rendent état, validation et groupes explicites et testables.',[o('a','Une variable libre par champ','La validation se disperse.'),o('b','Un formulaire réactif','Modèle explicite et testable.'),o('c','document.querySelector','Cela contourne Angular.')]),
    q('db5','quiz','Compréhension','Que décompose [(value)] avec valueChange ?', 'a','La syntaxe combine [value] et (valueChange).',[o('a','Une entrée et une sortie','[value] + (valueChange).'),o('b','Deux interpolations','Aucune interpolation.'),o('c','Une injection','Sans rapport.')]),
  ]},
  { id: 'directives-pipes', title: 'Directives et pipes', category: 'Fondamentaux', icon: 'pi pi-filter', description: 'Agir sur la structure, le comportement et la présentation.', definition: 'Une directive enrichit ou structure une vue. Un pipe transforme une valeur pour son affichage sans modifier la donnée source. Un pipe pur est recalculé quand ses entrées changent ; un pipe impur peut être rappelé à chaque vérification.', mentalModel: 'Directive : agir sur la vue ; pipe : produire une représentation ; pureté : décider quand la transformation doit être recalculée.', rule: 'Privilégie les pipes purs et réserve pure: false aux cas exceptionnels, mesurés et justifiés.', labRoute: '/lab/fondamentaux/directives-pipes', questions: [
    q('dp1','quiz','Compréhension','Directive structurelle et directive d’attribut : quelle différence ?', 'b','La première crée ou retire des vues ; la seconde modifie un élément existant.',[o('a','TypeScript contre HTML','Les deux appartiennent à Angular.'),o('b','Structure contre comportement','Création/retrait versus modification.'),o('c','Aucune différence','Leur impact diffère.')]),
    q('dp2','code-diagnostic','Lecture de code','Pourquoi track user.id est-il important ?', 'a','Une identité stable permet de réutiliser la bonne vue lors des mises à jour.',[o('a','Pour identifier et réutiliser la vue','Meilleur suivi des éléments.'),o('b','Pour trier la liste','track ne change pas l’ordre.'),o('c','Pour charger users','Les données existent déjà.')],`@for (user of users; track user.id) {\n  <user-card [user]="user" />\n}`),
    q('dp3','code-completion','Mise en pratique','Quel pipe formate cette date ?', 'c','Le pipe date produit la représentation demandée sans modifier la valeur source.',[o('a','format','Pas un pipe standard.'),o('b','datetime','Nom incorrect.'),o('c','date','DatePipe.')],`{{ createdAt | ___:'dd/MM/yyyy' }}`),
    q('dp4','architecture','Décision','Un pipe impur exécute un calcul lourd à chaque vérification. Que faire ?', 'b','Un calcul pur ou mémorisé évite des exécutions permanentes et implicites.',[o('a','Ajouter d’autres pipes impurs','Le coût augmente.'),o('b','Rendre le calcul pur ou mémorisé','Recalcul lorsque les entrées changent.'),o('c','Masquer en CSS','Le calcul continuerait.')]),
    q('dp5','quiz','Compréhension','Un pipe doit-il déclencher une requête HTTP ?', 'c','Un pipe doit rester une transformation prévisible ; les effets appartiennent à une couche de données.',[o('a','Toujours','Mélange effets et présentation.'),o('b','Seulement dans @for','La boucle ne sécurise pas l’effet.'),o('c','Non','Chargement et présentation restent séparés.')]),
  ]},
  { id: 'injection-dependances', title: 'Injection de dépendances', category: 'Fondamentaux', icon: 'pi pi-sitemap', description: 'Comprendre tokens, providers, injecteurs et durées de vie.', definition: 'L’injection de dépendances permet de demander une dépendance à Angular plutôt que de la construire avec new. Angular recherche un provider à partir d’un token dans la hiérarchie des injecteurs.', mentalModel: 'Le token est la clé, le provider explique comment obtenir la valeur et l’injecteur possède l’instance dans une portée donnée.', rule: 'Place le provider à l’endroit dont la durée de vie et le partage correspondent réellement au besoin.', labRoute: '/lab/fondamentaux/injection-dependances', questions: [
    q('di1','code-diagnostic','Lecture de code','Deux UserPage sont rendues. Combien de UserStore ?', 'c','Chaque instance du composant possède son injecteur local et son propre store.',[o('a','Aucun','Le service est demandé.'),o('b','Un global','Le provider n’est pas root.'),o('c','Deux','Une instance par UserPage.'),o('d','Quatre','inject() ne multiplie pas les instances.')],`@Component({ providers: [UserStore] })\nexport class UserPage { store = inject(UserStore); }`),
    q('di2','quiz','Compréhension',"Que produit providedIn: 'root' dans le cas habituel ?", 'a','Le service est fourni et partagé dans l’injecteur racine de l’application.',[o('a','Une instance partagée','Portée racine.'),o('b','Une instance par composant','Provider local.'),o('c','Une instance par méthode','Aucune portée de ce type.')]),
    q('di3','code-completion','Mise en pratique','Comment fournir DraftStore localement ?', 'b','providers: [DraftStore] attache le provider à l’injecteur du composant.',[o('a','imports: [DraftStore]','Un service n’est pas une dépendance de template.'),o('b','providers: [DraftStore]','Provider local.'),o('c','styles: [DraftStore]','Sans rapport.')],`@Component({ standalone: true,\n  ___\n})`),
    q('di4','architecture','Décision','Un brouillon doit être isolé entre deux éditeurs ouverts. Où fournir le store ?', 'c','Le provider du composant Editor crée une instance distincte par éditeur.',[o('a','Au bootstrap','État global.'),o('b',"providedIn: 'root'",'État partagé.'),o('c','Dans providers de Editor','État local à chaque éditeur.')]),
    q('di5','quiz','Compréhension','Pourquoi utiliser InjectionToken ?', 'b','Il identifie au runtime une valeur qui n’a pas de classe, comme une configuration.',[o('a','Pour remplacer TypeScript','Il coopère avec TypeScript.'),o('b','Pour identifier une valeur au runtime','Une interface seule disparaît.'),o('c','Pour créer une route','Sans rapport.')]),
  ]},
  { id: 'cycle-vie-rendu', title: 'Cycle de vie et rendu', category: 'Fondamentaux', icon: 'pi pi-refresh', description: 'Initialiser, observer et nettoyer au bon moment.', definition: 'Le cycle de vie décrit les étapes traversées par une instance de composant : création, réception des entrées, rendu, mises à jour et destruction. Les hooks permettent d’exécuter du code à une étape précise.', mentalModel: 'Données disponibles, DOM disponible et instance encore vivante sont trois questions différentes.', rule: 'Utilise un hook uniquement si le traitement dépend réellement d’un moment du cycle de vie.', labRoute: '/lab/fondamentaux/cycle-vie-rendu', questions: [
    q('lc1','quiz','Compréhension','Quand ngOnInit est-il appelé ?', 'b','Une fois après l’initialisation des entrées initiales du composant.',[o('a','Avant le constructeur','Impossible.'),o('b','Après les entrées initiales','Hook d’initialisation.'),o('c','Après chaque clic','Il ne se répète pas ainsi.')]),
    q('lc2','code-diagnostic','Lecture de code','Quel risque porte cette souscription ?', 'a','Sans nettoyage, elle peut continuer après la destruction du composant.',[o('a','Fuite et effets après destruction','La souscription reste active.'),o('b','Rappel du constructeur','Sans rapport.'),o('c','Intervalle synchrone','Il reste asynchrone.')],`ngOnInit() {\n  interval(1000).subscribe(v => this.value = v);\n}`),
    q('lc3','code-completion','Mise en pratique','Quel opérateur lie la souscription à la destruction ?', 'c','takeUntilDestroyed arrête le flux avec le DestroyRef associé.',[o('a','retry','Relance après erreur.'),o('b','takeWhileAlive','N’existe pas nativement.'),o('c','takeUntilDestroyed','Interop Angular/RxJS.')],`source$.pipe(____()).subscribe();`),
    q('lc4','architecture','Décision','Tu dois mesurer un élément après son rendu. Quelle approche ?', 'b','afterNextRender planifie le travail après le prochain rendu.',[o('a','Le constructeur','DOM indisponible.'),o('b','afterNextRender','Moment ciblé après rendu.'),o('c','Chaque ngAfterViewChecked','Trop fréquent.')]),
    q('lc5','quiz','Compréhension','Quel hook permet le nettoyage manuel final ?', 'a','ngOnDestroy intervient juste avant la destruction de l’instance.',[o('a','ngOnDestroy','Nettoyage final.'),o('b','ngOnChanges','Changements d’inputs.'),o('c','ngDoCheck','Vérification personnalisée.')]),
  ]},
  { id: 'http-intercepteurs', title: 'HTTP et intercepteurs', category: 'Fondamentaux', icon: 'pi pi-cloud', description: 'Effectuer des requêtes typées et centraliser le transverse.', definition: 'HttpClient construit des requêtes et retourne des Observables froids. Un intercepteur entoure leur exécution pour appliquer une préoccupation réellement transverse comme l’authentification ou la journalisation.', mentalModel: 'Le service parle le langage métier ; l’intercepteur applique une règle technique commune ; le composant représente l’état de l’interface.', rule: 'Ne masque pas les erreurs et ne duplique pas dans les composants ce qui appartient au service ou au pipeline HTTP.', labRoute: '/lab/fondamentaux/http-intercepteurs', questions: [
    q('ht1','quiz','Compréhension','Que retourne HttpClient.get<T>() ?', 'b','Il retourne un Observable<T> froid représentant la réponse.',[o('a','Directement T','La réponse est asynchrone.'),o('b','Observable<T>','Flux HTTP.'),o('c','Toujours Promise<T>','Ce n’est pas l’API par défaut.')]),
    q('ht2','code-diagnostic','Lecture de code','Pourquoi deux requêtes peuvent-elles partir ?', 'a','Chaque souscription indépendante exécute l’Observable HTTP froid.',[o('a','Une requête par souscription','Observable froid.'),o('b','La constante est dupliquée','Une seule variable.'),o('c','HttpClient double toujours','Cela dépend des souscriptions.')],`const users$ = http.get('/api/users');\nusers$.subscribe();\nusers$.subscribe();`),
    q('ht3','code-completion','Mise en pratique','Quelle configuration active HttpClient au bootstrap ?', 'c','provideHttpClient enregistre les providers HTTP dans l’application standalone.',[o('a','new HttpClient','Dépendances absentes.'),o('b','HttpClientModule','Ce n’est pas un appel ici.'),o('c','provideHttpClient','API de provider moderne.')],`bootstrapApplication(AppComponent, {\n  providers: [____()]\n});`),
    q('ht4','architecture','Décision','Où ajouter systématiquement un jeton d’authentification ?', 'b','Un intercepteur centralise cette préoccupation transverse et évite les oublis.',[o('a','Dans chaque composant','Duplication.'),o('b','Dans un intercepteur','Traitement centralisé.'),o('c','Dans le template','Il ne construit pas les requêtes.')]),
    q('ht5','quiz','Compréhension','Un intercepteur doit-il avaler toutes les erreurs ?', 'c','Il traite le global puis propage l’erreur lorsque le contexte métier doit décider.',[o('a','Oui, toujours','L’information disparaît.'),o('b','Oui, en retournant null','Le contrat devient ambigu.'),o('c','Non, propager si nécessaire','Responsabilités séparées.')]),
  ]},
];

export const TRAINING_LESSONS = FUNDAMENTALS_LESSONS;
export const findTrainingLesson = (id: string | null): TrainingLesson | undefined => TRAINING_LESSONS.find(lesson => lesson.id === id);
